import {
  teamsDarkTheme,
  teamsLightTheme,
  brandRamp,
  type Theme,
} from '@fluentui/react-components'

const cyanBrand: typeof brandRamp = {
  10: '#030303',
  20: '#0d1a1a',
  30: '#003338',
  40: '#004a52',
  50: '#00636d',
  60: '#007d89',
  70: '#008c99',
  80: '#009ba8',
  90: '#00aab8',
  100: '#00b8c8',
  110: '#00c8d8',
  120: '#00d8e8',
  130: '#00e8f8',
  140: '#33f0f8',
  150: '#66f4f8',
  160: '#99f8f8',
} as typeof brandRamp

export const appDarkTheme: Theme = {
  ...teamsDarkTheme,
  colorBrandForeground1: cyanBrand[110],
  colorBrandForeground2: cyanBrand[120],
  colorBrandBackground: cyanBrand[80],
  colorBrandBackgroundHover: cyanBrand[70],
  colorBrandBackgroundPressed: cyanBrand[60],
  colorBrandBackgroundSelected: cyanBrand[80],
  colorBrandBackgroundStatic: cyanBrand[80],
  colorBrandForegroundLink: cyanBrand[110],
  colorBrandForegroundLinkHover: cyanBrand[120],
  colorBrandForegroundLinkPressed: cyanBrand[100],
  colorBrandForegroundLinkSelected: cyanBrand[110],
  colorCompoundBrandForeground1: cyanBrand[110],
  colorCompoundBrandForeground1Hover: cyanBrand[120],
  colorCompoundBrandForeground1Pressed: cyanBrand[100],
  colorCompoundBrandBackground: cyanBrand[80],
  colorCompoundBrandBackgroundHover: cyanBrand[70],
  colorCompoundBrandBackgroundPressed: cyanBrand[60],
  colorBrandStroke1: cyanBrand[110],
  colorBrandStroke2: cyanBrand[80],
}

export const appLightTheme: Theme = {
  ...teamsLightTheme,
  colorBrandForeground1: cyanBrand[60],
  colorBrandForeground2: cyanBrand[70],
  colorBrandBackground: cyanBrand[100],
  colorBrandBackgroundHover: cyanBrand[110],
  colorBrandBackgroundPressed: cyanBrand[120],
  colorBrandBackgroundSelected: cyanBrand[100],
  colorBrandBackgroundStatic: cyanBrand[100],
  colorBrandForegroundLink: cyanBrand[60],
  colorBrandForegroundLinkHover: cyanBrand[70],
  colorBrandForegroundLinkPressed: cyanBrand[50],
  colorBrandForegroundLinkSelected: cyanBrand[60],
  colorCompoundBrandForeground1: cyanBrand[60],
  colorCompoundBrandForeground1Hover: cyanBrand[70],
  colorCompoundBrandForeground1Pressed: cyanBrand[50],
  colorCompoundBrandBackground: cyanBrand[100],
  colorCompoundBrandBackgroundHover: cyanBrand[110],
  colorCompoundBrandBackgroundPressed: cyanBrand[120],
  colorBrandStroke1: cyanBrand[60],
  colorBrandStroke2: cyanBrand[100],
}
